"""Create an MJX-friendly collision variant of the Microduck walk scene.

Replaces the two sole collision MESH geoms (7900-vertex convex hulls -> GiB-scale
XLA kernels per env) with BOX primitives of the same footprint/pose, and bakes
MJX-tuned solver iterations into the scene. Visual meshes (contype=0) never enter
collision kernels and are left untouched. This mirrors the official 'walk'
collision family (feet-only) — physics for standing/walking is unchanged apart
from sole corners being sharp instead of rounded.

Writes: robot_walk_mjx.xml, scene_walk_mjx.xml (next to the originals).
"""

import re
import numpy as np
import mujoco

SRC = "src/mjlab_microduck/robot/microduck"
model = mujoco.MjModel.from_xml_path(f"{SRC}/scene_walk.xml")


def mesh_bbox(mesh_name):
    mi = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_MESH, mesh_name)
    adr = model.mesh_vertadr[mi]
    n = model.mesh_vertnum[mi]
    v = model.mesh_vert[adr : adr + n]
    lo, hi = v.min(axis=0), v.max(axis=0)
    center = (lo + hi) / 2
    extent = (hi - lo) / 2
    return center, extent


robot_xml = open(f"{SRC}/robot_walk.xml").read()
scene_xml = open(f"{SRC}/scene_walk.xml").read()

for side in ("left", "right"):
    gname = f"{side}_foot_collision"
    gid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, gname)
    mesh_name = "sole_left" if side == "left" else "sole_right"
    center, extent = mesh_bbox(mesh_name)
    # box size in geom-local axes; shift geom pos so the box covers the same
    # span as the mesh (mesh vertices are in mesh frame, box center = mesh bbox
    # center expressed in the geom frame; the mesh geom applies pos+quat to the
    # mesh vertices, so a box of the bbox half-extents at pos+R*center with the
    # same quat is equivalent).
    c_local = center
    size = extent
    old_geom = next(
        l for l in robot_xml.splitlines() if f'name="{gname}"' in l
    )
    quat_attr = re.search(r'quat="([^"]+)"', old_geom)
    if quat_attr is None:
        raise RuntimeError("expected quat on the sole geoms")
    q = np.array([float(x) for x in quat_attr.group(1).split()])
    R = np.zeros(9)
    mujoco.mju_quat2Mat(R, q)
    R = R.reshape(3, 3)
    pos_attr = re.search(r'pos="([^"]+)"', old_geom)
    pos = np.array([float(x) for x in pos_attr.group(1).split()])
    new_pos = pos + R @ c_local
    new_geom = (
        f'<geom type="box" name="{gname}" class="collision" '
        f'pos="{new_pos[0]:.6f} {new_pos[1]:.6f} {new_pos[2]:.6f}" '
        f'quat="{quat_attr.group(1)}" '
        f'size="{size[0]:.5f} {size[1]:.5f} {size[2]:.5f}"/>'
    )
    robot_xml = robot_xml.replace(old_geom, new_geom)
    print(f"{gname}: mesh -> box, size={np.round(size,4)}, pos {np.round(pos,4)} -> {np.round(new_pos,4)}")

open(f"{SRC}/robot_walk_mjx.xml", "w").write(robot_xml)

scene_xml = scene_xml.replace(
    '<include file="robot_walk.xml" />',
    '<!-- MJX variant: box soles + tuned solver (generated by make_mjx_variant.py) -->\n    <include file="robot_walk_mjx.xml" />',
)
# tracking camera for rollout rendering
scene_xml = scene_xml.replace(
    "<worldbody>",
    '<worldbody>\n        <camera name="side" mode="track" target="trunk_base" '
    'pos="0.38 -0.42 0.18" xyaxes="-0.75 0.66 0 0.1 0.12 1"/>',
)
# bake MJX-tuned solver iterations (the CPU-tuned 100/50 explodes the batched HLO)
scene_xml = scene_xml.replace(
    "<mujoco model=\"scene\">",
    "<mujoco model=\"scene\">\n  <option timestep=\"0.002\" solver=\"Newton\" iterations=\"25\" ls_iterations=\"10\"/>",
)
open(f"{SRC}/scene_walk_mjx.xml", "w").write(scene_xml)
print("wrote robot_walk_mjx.xml, scene_walk_mjx.xml")

# ---- verify the variant loads and matches ----
mv = mujoco.MjModel.from_xml_path(f"{SRC}/scene_walk_mjx.xml")
assert mv.nq == model.nq and mv.nu == model.nu, "topology changed!"
assert mv.opt.iterations == 25 and mv.opt.ls_iterations == 10, "option not applied"
for side in ("left", "right"):
    gid_v = mujoco.mj_name2id(mv, mujoco.mjtObj.mjOBJ_GEOM, f"{side}_foot_collision")
    assert mv.geom_type[gid_v] == mujoco.mjtGeom.mjGEOM_BOX, f"{side} sole not a box"
print(f"variant OK: nq={mv.nq} nu={mv.nu} ngeom={mv.ngeom} iterations={mv.opt.iterations}")

# ---- CPU settle parity: hold STAND 3 s from noisy inits, check height+tilt ----
def settle(mm, label):
    d = mujoco.MjData(mm)
    sid = mujoco.mj_name2id(mm, mujoco.mjtObj.mjOBJ_KEY, "STAND")
    rng = np.random.default_rng(0)
    z_end, tilt_end = [], []
    for _ in range(3):
        mujoco.mj_resetDataKeyframe(mm, d, sid)
        d.qpos[7:] += rng.normal(0, 0.03, 14)
        d.qvel[:] = rng.normal(0, 0.02, mm.nv)
        mujoco.mj_forward(mm, d)
        for _ in range(1500):  # 3 s
            mujoco.mj_step(mm, d)
        z_end.append(d.qpos[2])
        # tilt = angle of trunk z axis from vertical
        quat = d.qpos[3:7]
        R = np.zeros(9)
        mujoco.mju_quat2Mat(R, quat)
        tilt_end.append(np.degrees(np.arccos(np.clip(R[8], -1, 1))))
    print(f"{label}: z={np.mean(z_end):.4f}±{np.std(z_end):.4f} m, tilt={np.mean(tilt_end):.1f}±{np.std(tilt_end):.1f} deg")

settle(model, "原版 mesh soles")
settle(mv, "MJX box soles ")
